TypedDag::Configuration.set edge_class_name: 'Relation',
                            node_class_name: 'Message',
                            from_column: 'ancestor_id',
                            to_column: 'descendant_id',
                            types: { hierarchy: { from: { name: :parent, limit: 1 },
                                                  to: :children,
                                                  all_from: :ancestors,
                                                  all_to: :descendants },
                                     invalidate: { from: :invalidated_by,
                                                   to: :invalidates,
                                                   all_from: :all_invalidated_by,
                                                   all_to: :all_invalidates } }
